/*eslint-disable */
var EK_MOVES = {
    Acid: { target: 'allAdjacentFoes' },
    Bide: { makesContact: true },
    Bind: { makesContact: true },
    Blizzard: { target: 'allAdjacentFoes' },
    Clamp: { makesContact: true },
    'Comet Punch': { makesContact: true },
    Counter: { makesContact: true },
    Crunch: { makesContact: true },
    Detect: { priority: 3 },
    Endure: { priority: 4 },
    Protect: { priority: 3 },
    Dig: { makesContact: true },
    'Double Kick': { makesContact: true },
    'Double Slap': { makesContact: true },
    Explosion: { target: 'allAdjacent' },
    Flail: { makesContact: true },
    Fly: { makesContact: true },
    'Fury Attack': { makesContact: true },
    'Fury Swipes': { makesContact: true },
    'Hi Jump Kick': { makesContact: true },
    'Jump Kick': { makesContact: true },
    'Leech Life': { makesContact: true },
    Outrage: { makesContact: true },
    'Petal Dance': { makesContact: true },
    Pursuit: { makesContact: true },
    Rage: { makesContact: true },
    'Rapid Spin': { makesContact: true },
    'Razor Wind': { target: 'allAdjacentFoes' },
    Reversal: { makesContact: true },
    'Rock Smash': { makesContact: true },
    'Self-Destruct': { target: 'allAdjacent' },
    'Skull Bash': { makesContact: true },
    Stomp: { makesContact: true },
    Struggle: { makesContact: true },
    Surf: { target: 'allAdjacentFoes' },
    Thief: { makesContact: true },
    Thrash: { makesContact: true },
    'Triple Kick': { makesContact: true, multihit: 3 },
    'Vine Whip': { makesContact: true },
    Waterfall: { makesContact: true },
    Wrap: { makesContact: true },
    Crabhammer: { makesContact: true },
    'Double-Edge': { recoil: [1, 3], makesContact: true },
    Earthquake: { target: 'allAdjacent' },
    'Extreme Speed': { makesContact: true },
    'Fury Cutter': { makesContact: true },
    'Heal Bell': { isSound: true },
    Magnitude: { target: 'allAdjacent' },
    Roar: { isSound: true },
    Submission: { makesContact: true },
    Tackle: { makesContact: true },
    'Take Down': { makesContact: true },
    Twister: { target: 'allAdjacentFoes' },
    'Body Slam': { makesContact: true },
    Bubble: { target: 'allAdjacentFoes' },
    Growl: { isSound: true, target: 'allAdjacentFoes' },
    Lick: { makesContact: true },
    'Perish Song': { isSound: true },
    Screech: { isSound: true },
    Sing: { isSound: true },
    Snore: { isSound: true },
    'String Shot': { target: 'allAdjacentFoes' },
    Supersonic: { isSound: true },
    'Sweet Scent': { target: 'allAdjacentFoes' },
    Rollout: { makesContact: true },
    Constrict: { makesContact: true },
    'Dizzy Punch': { makesContact: true },
    Frustration: { makesContact: true },
    'Hyper Fang': { makesContact: true },
    'Karate Chop': { makesContact: true },
    'Low Kick': { bp: 0, makesContact: true },
    Return: { makesContact: true },
    'Rolling Kick': { makesContact: true },
    Bite: { makesContact: true },
    'Cross Chop': { makesContact: true },
    Cut: { makesContact: true },
    'Drill Peck': { makesContact: true },
    'Dynamic Punch': { makesContact: true },
    'False Swipe': { makesContact: true },
    'Fire Punch': { makesContact: true },
    'Flame Wheel': { makesContact: true },
    Guillotine: { makesContact: true },
    Headbutt: { makesContact: true },
    'Horn Attack': { makesContact: true },
    'Horn Drill': { makesContact: true },
    'Ice Punch': { makesContact: true },
    'Icy Wind': { target: 'allAdjacentFoes' },
    'Iron Tail': { makesContact: true },
    Leer: { target: 'allAdjacentFoes' },
    'Mach Punch': { makesContact: true },
    Megahorn: { makesContact: true },
    'Mega Kick': { makesContact: true },
    'Mega Punch': { makesContact: true },
    'Metal Claw': { makesContact: true },
    Peck: { makesContact: true },
    Pound: { makesContact: true },
    'Powder Snow': { target: 'allAdjacentFoes' },
    'Quick Attack': { makesContact: true },
    'Razor Leaf': { target: 'allAdjacentFoes' },
    'Rock Slide': { target: 'allAdjacentFoes' },
    Scratch: { makesContact: true },
    'Seismic Toss': { makesContact: true },
    'Shadow Strike': { makesContact: true },
    Slam: { makesContact: true },
    Slash: { makesContact: true },
    Spark: { makesContact: true },
    'Steel Wing': { makesContact: true },
    Strength: { makesContact: true },
    'Super Fang': { makesContact: true },
    Swift: { target: 'allAdjacentFoes' },
    'Tail Whip': { target: 'allAdjacentFoes' },
    'Thunder Punch': { makesContact: true },
    'Vise Grip': { makesContact: true },
    'Vital Throw': { makesContact: true },
    'Wing Attack': { makesContact: true },
    'Arm Thrust': {
        bp: 15,
        type: 'Fighting',
        multihit: [2, 5],
        makesContact: true
    },
    'Drill Run': { bp: 80, type: 'Ground' },
    'Earth Power': { bp: 90, type: 'Ground' },
    'Gunk Shot': { bp: 120, type: 'Poison' },
    'Head Smash': { bp: 150, type: 'Rock', recoil: [1, 3] },
    'Wild Charge': { bp: 90, type: 'Electric', recoil: [1, 3] },
    'Draco Meteor': { bp: 120, type: 'Dragon', recoil: [1, 3] },
    'Force Palm': { bp: 60, type: 'Fighting' },
    'Shadow Sneak': { bp: 40, type: 'Ghost' },
    'Air Slash': { bp: 80, type: 'Flying' },
    'Flash Cannon': { bp: 90, type: 'Steel' },
    'Ice Shard': { bp: 40, type: 'Ice' },
    'X-scissors': { bp: 80, type: 'Bug' },
    Assist: { bp: 0, category: 'Status', type: 'Normal' },
    Astonish: { bp: 30, type: 'Ghost', makesContact: true },
    Block: { bp: 0, category: 'Status', type: 'Normal' },
    Bounce: { bp: 85, type: 'Flying', makesContact: true },
    'Bullet Seed': { bp: 25, type: 'Grass', multihit: 2 },
    Camouflage: { bp: 0, category: 'Status', type: 'Normal' },
    Charge: { bp: 0, category: 'Status', type: 'Electric' },
    Covet: { bp: 40, type: 'Normal' },
    Dive: { bp: 60, type: 'Water', makesContact: true },
    'Doom Desire': { bp: 120, type: 'Steel' },
    Extrasensory: { bp: 80, type: 'Psychic' },
    'Fake Out': { bp: 40, type: 'Normal', priority: 1 },
    'Follow Me': { bp: 0, category: 'Status', type: 'Normal', priority: 3 },
    Hail: { bp: 0, category: 'Status', type: 'Ice' },
    'Icicle Spear': { bp: 10, type: 'Ice', multihit: [2, 5] },
    Ingrain: { bp: 0, category: 'Status', type: 'Grass' },
    'Knock Off': { bp: 20, type: 'Dark', makesContact: true },
    'Leaf Blade': { bp: 95, type: 'Grass', makesContact: true },
    'Magic Coat': { bp: 0, category: 'Status', type: 'Psychic', priority: 4 },
    Memento: { bp: 0, category: 'Status', type: 'Dark' },
    'Nature Power': { bp: 0, category: 'Status', type: 'Normal' },
    'Needle Arm': { bp: 95, type: 'Grass', makesContact: true },
    'Odor Sleuth': { bp: 0, category: 'Status', type: 'Normal' },
    Overheat: { bp: 120, type: 'Fire', makesContact: true, recoil: [1, 3] },
    Revenge: { bp: 60, type: 'Fighting', makesContact: true },
    'Rock Blast': { bp: 25, type: 'Rock', multihit: [2, 5] },
    'Role Play': { bp: 0, category: 'Status', type: 'Psychic' },
    'Sand Tomb': { bp: 15, type: 'Ground' },
    'Skill Swap': { bp: 0, category: 'Status', type: 'Psychic' },
    'Smelling Salts': { bp: 60, type: 'Normal', makesContact: true },
    'Spit Up': { bp: 100, type: 'Normal' },
    Stockpile: { bp: 0, category: 'Status', type: 'Normal' },
    Swallow: { bp: 0, category: 'Status', type: 'Normal' },
    Taunt: { bp: 0, category: 'Status', type: 'Dark' },
    'Teeter Dance': { bp: 0, category: 'Status', type: 'Normal', target: 'allAdjacent' },
    Tickle: { bp: 0, category: 'Status', type: 'Normal' },
    Trick: { bp: 0, category: 'Status', type: 'Psychic' },
    Uproar: { bp: 50, type: 'Normal', isSound: true },
    'Volt Tackle': { bp: 120, type: 'Electric', recoil: [1, 3], makesContact: true },
    'Weather Ball': { bp: 50, type: 'Normal' },
    'Weather Ball AI': { bp: 100, type: 'Normal' },
    Aromatherapy: { bp: 0, category: 'Status', type: 'Grass' },
    'Brick Break': { bp: 75, type: 'Fighting', makesContact: true },
    Endeavor: { bp: 0, type: 'Normal', makesContact: true },
    'Focus Punch': { bp: 150, type: 'Fighting', makesContact: true },
    Imprison: { bp: 0, category: 'Status', type: 'Psychic' },
    'Mud Sport': { bp: 0, category: 'Status', type: 'Ground' },
    Recycle: { bp: 0, category: 'Status', type: 'Normal' },
    'Secret Power': { bp: 70, type: 'Normal' },
    'Sky Uppercut': { bp: 90, type: 'Fighting', makesContact: true },
    'Slack Off': { bp: 0, category: 'Status', type: 'Normal' },
    Snatch: { bp: 0, category: 'Status', type: 'Dark', priority: 4 },
    'Tail Glow': { bp: 0, category: 'Status', type: 'Bug' },
    Torment: { bp: 0, category: 'Status', type: 'Dark' },
    'Water Sport': { bp: 0, category: 'Status', type: 'Water' },
    Wish: { bp: 0, category: 'Status', type: 'Normal' },
    'Air Cutter': { bp: 55, type: 'Flying', target: 'allAdjacentFoes' },
    Facade: { bp: 70, type: 'Normal', makesContact: true },
    'Grass Whistle': { bp: 0, category: 'Status', type: 'Grass', isSound: true },
    'Heat Wave': { bp: 100, type: 'Fire', target: 'allAdjacentFoes' },
    'Hyper Voice': { bp: 120, type: 'Normal', isSound: true, target: 'allAdjacentFoes' },
    'Metal Sound': { bp: 0, category: 'Status', type: 'Steel', isSound: true },
    'Meteor Mash': { bp: 100, type: 'Steel', makesContact: true },
    'Muddy Water': { bp: 95, type: 'Water', target: 'allAdjacentFoes' },
    'Poison Fang': { bp: 90, type: 'Poison', makesContact: true },
    'Rock Tomb': { bp: 55, type: 'Rock' },
    'Will-O-Wisp': { bp: 0, category: 'Status', type: 'Fire' },
    'Ice Ball': { bp: 30, type: 'Ice', makesContact: true },
    'Sheer Cold': { bp: 0, type: 'Ice' },
    Howl: { bp: 0, category: 'Status', type: 'Normal' },
    'Luster Purge': { bp: 90, type: 'Psychic' },
    'Mist Ball': { bp: 90, type: 'Psychic' },
    'Psycho Boost': { bp: 140, type: 'Psychic', recoil: [1, 4] },
    Refresh: { bp: 0, category: 'Status', type: 'Normal' },
    'Signal Beam': { bp: 75, type: 'Bug' },
    'Silver Wind': { bp: 60, type: 'Bug' },
    'Aerial Ace': { bp: 60, type: 'Flying', makesContact: true },
    'Blast Burn': { bp: 150, type: 'Fire' },
    'Blaze Kick': { bp: 100, type: 'Fire', makesContact: true },
    'Bulk Up': { bp: 0, category: 'Status', type: 'Fighting' },
    'Calm Mind': { bp: 0, category: 'Status', type: 'Psychic' },
    'Cosmic Power': { bp: 0, category: 'Status', type: 'Psychic' },
    'Crush Claw': { bp: 100, type: 'Normal', makesContact: true },
    'Dragon Claw': { bp: 80, type: 'Dragon', makesContact: true },
    'Dragon Dance': { bp: 0, category: 'Status', type: 'Dragon' },
    Eruption: { bp: 150, type: 'Fire', target: 'allAdjacentFoes' },
    'Fake Tears': { bp: 0, category: 'Status', type: 'Dark' },
    'Feather Dance': { bp: 0, category: 'Status', type: 'Flying' },
    Flatter: { bp: 0, category: 'Status', type: 'Dark' },
    'Frenzy Plant': { bp: 150, type: 'Grass' },
    Grudge: { bp: 0, category: 'Status', type: 'Ghost' },
    'Helping Hand': { bp: 0, category: 'Status', type: 'Normal', priority: 5 },
    'Hydro Cannon': { bp: 150, type: 'Water' },
    'Iron Defense': { bp: 0, category: 'Status', type: 'Steel' },
    'Magical Leaf': { bp: 60, type: 'Grass' },
    'Mud Shot': { bp: 55, type: 'Ground' },
    'Poison Tail': { bp: 120, type: 'Poison', makesContact: true },
    'Shadow Punch': { bp: 70, type: 'Ghost', makesContact: true },
    'Shock Wave': { bp: 60, type: 'Electric' },
    Superpower: { bp: 120, type: 'Fighting', recoil: [1, 3], makesContact: true },
    'Water Pulse': { bp: 60, type: 'Water' },
    'Water Spout': { bp: 150, type: 'Water', target: 'allAdjacentFoes', recoil: [1, 4] },
    Yawn: { bp: 0, category: 'Status', type: 'Normal' }
};

$(document).ready(function () {
    moves = {...moves, ...EK_MOVES};
    var moveOptions = getSelectOptions(Object.keys(moves), true)
    $("select.move-selector").find("option").remove().end().append(moveOptions);
});

/*eslint-enable */
